### ISSUE TITLE
银联支付成功点击返回商户BUG

### ISSUE THREAD

**Issue by Crazykulou** [Javen205/IJPay-Demo#10]
`/**
	 * 前台回调
	 */
	@RequestMapping(value = "/frontRcvResponse",method={RequestMethod.POST,RequestMethod.GET})
	public String frontRcvResponse(HttpServletRequest request,HttpServletResponse response) {
		try {
			logger.info("FrontRcvResponse前台接收报文返回开始");

			String encoding = "UTF-8";
			logger.info("返回报文中encoding=[" + encoding + "]");
			String readData = HttpKit.readData(request);
			Map<String, String> respParam = getAllRequestParamToMap(readData);`
Spring-boot2x中的银联接口里HttpKit.readData方法取request内取reader的值拿不到

**Comment by Javen205** [comment]
在群里有看到交流这个问题  是你吗？  这个问题解决了吧

**Comment by Crazykulou** [comment]
> 在群里有看到交流这个问题 是你吗？ 这个问题解决了吧

问题已经解决了
