### ISSUE TITLE
sl4j日志文件冲突，见图

### ISSUE THREAD

**Issue by WhenCoding** [Javen205/IJPay-Demo#13]
![image](https://user-images.githubusercontent.com/28731024/57521855-ef8d3780-7353-11e9-8a56-04575504058c.png)

**Comment by Javen205** [comment]
解决方案参考  https://blog.csdn.net/wohaqiyi/article/details/81009689

**Comment by WhenCoding** [comment]
🙏

**Comment by WhenCoding** [comment]
> 解决方案参考 https://blog.csdn.net/wohaqiyi/article/details/81009689

🙏
