### ISSUE TITLE
试了下，不能读取alipay wxpay properties文件到bean

### ISSUE THREAD

**Issue by mingj** [Javen205/IJPay-Demo#3]
不知道是不是最新版本的问题，但是目前我是没有测试成功，请问作者有这个问题吗？ spring boot 版本

**Comment by Javen205** [comment]
默认读取的是`dev`下的配置，你`clone`下来的是没有此文件夹的需要自己复制`production`文件夹并将其修改为`dev`再修改配置文件中的参数。[视频地址](http://blog.csdn.net/zyw_java/article/details/72571535)

**Comment by mingj** [comment]
hi  这个操作我是做过的，但是目前还是不能通过bean 加载properties文件，还在找原因.

**Comment by Javen205** [comment]
@mingj Hello 你这边找到原因了吗？ 如果解决了，来分享一下心得。

**Comment by mingj** [comment]
没有找到原因 换了种方式实现。谢谢

**Comment by Javen205** [comment]
好的，再遇到问题及时反馈交流。
