### ISSUE TITLE
有部署的步骤吗

### ISSUE THREAD

**Issue by jwcjf** [Javen205/IJPay-Demo#4]

**Comment by Javen205** [comment]
第一：修改resources下对应支付的属性文件
第二：如果你是本地测试需要做[端口映射](http://blog.csdn.net/zyw_java/article/details/70341106)
第三：本地启动测试如果是JFinal版本直接运行APPConfig，如果Springboot 版本直接运行DemoApplication
第四：如果是打包上服务器运行，部署步骤与普通的Java web maven项目一样。打war包扔到Tomcat的webapps中即可
