### ISSUE TITLE
微信扫码支付模式二 openId非必须

### ISSUE THREAD

**Issue by hunao0221** [Javen205/IJPay-Demo#8]
WxPayController#scanCode2
模式二不需要传openid。
`trade_type=JSAPI时（即公众号支付），此参数必传，此参数为微信用户在商户对应appid下的唯一标识`

**Comment by Javen205** [comment]
之前测试是需要openId的。现在的接口你可以尝试一下不使用openId来支付试试。

有结果了麻烦告知一下，谢谢。

**Comment by Javen205** [comment]
@hunao0221  如果没有问题 我就close掉了
